# Generated by Django 4.1 on 2022-09-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkIn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='guest',
            new_name='memo',
        ),
    ]
