# Generated by Django 4.1 on 2022-09-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkIn', '0002_rename_guest_guest_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='checkedIn',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='memo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
