# Generated by Django 4.1.2 on 2022-10-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkIn', '0003_alter_guest_checkedin_alter_guest_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='made_on',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
