# Generated by Django 4.1.2 on 2022-10-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkIn', '0004_guest_made_on_alter_guest_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='made_on',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
