# Generated by Django 4.1.2 on 2022-10-08 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('has_appointment', models.BooleanField(null=True)),
                ('Clientlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.clientlist')),
            ],
        ),
    ]
