# Generated by Django 4.1.2 on 2022-10-09 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('has_appt', models.BooleanField(null=True)),
                ('schedule_id', models.CharField(blank=True, editable=False, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='You made appt at ')),
            ],
        ),
        migrations.AddField(
            model_name='clientlist',
            name='phone_no',
            field=models.CharField(default='000-000-000', max_length=20),
        ),
        migrations.AddField(
            model_name='clientlist',
            name='timing',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Your appt time is '),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='appointment',
            name='clientlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.clientlist'),
        ),
    ]
