# Generated by Django 4.1.2 on 2022-10-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0002_appointment_clientlist_phone_no_clientlist_timing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlist',
            name='timing',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Your appt time is '),
        ),
    ]
