# Generated by Django 4.1.2 on 2022-10-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0004_clientlist_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='has_appt',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientlist',
            name='timing',
            field=models.DateTimeField(default='Oct. 10, 2022, 10:00 a.m.', verbose_name='Your appt time is '),
        ),
    ]
