# Generated by Django 4.1.2 on 2022-10-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0005_alter_appointment_has_appt_alter_clientlist_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlist',
            name='appt_date',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AlterField(
            model_name='clientlist',
            name='timing',
            field=models.DateTimeField(default='2023-01-01 10:00', verbose_name='Your appt time is '),
        ),
    ]
