# Generated by Django 4.1.2 on 2022-10-10 16:40

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0006_clientlist_appt_date_alter_clientlist_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlist',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='UTC'),
        ),
        migrations.AlterField(
            model_name='clientlist',
            name='timing',
            field=models.TimeField(default='10:00', verbose_name='Your appt time is '),
        ),
    ]
