# Generated by Django 4.1.2 on 2022-10-12 11:18

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0007_clientlist_time_zone_alter_clientlist_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlist',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Helsinki'),
        ),
    ]
