# Generated by Django 4.1.2 on 2022-10-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0008_alter_clientlist_time_zone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Account',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='memo',
            new_name='password',
        ),
    ]
