# Generated by Django 4.1.2 on 2022-10-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0009_rename_appointment_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='schedule_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='clientlist',
            name='schedule_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='clientlist',
            name='timestamp',
            field=models.DateTimeField(default='2023-10-25 14:30:59', verbose_name='You made appt at '),
        ),
    ]
