# Generated by Django 4.1.2 on 2022-10-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0010_remove_account_schedule_id_remove_account_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlist',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='You made appt at '),
        ),
    ]
