# Generated by Django 4.1.2 on 2022-10-18 14:57

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_no', models.CharField(default='000-000-000', max_length=20)),
                ('email', models.EmailField(default='example@gmail.com', max_length=200)),
                ('appt_date', models.DateField(default='2023-01-01')),
                ('timing', models.TimeField(default='10:00', verbose_name='Your appt time is ')),
                ('time_zone', timezone_field.fields.TimeZoneField(default='Europe/Helsinki')),
                ('schedule_id', models.CharField(blank=True, editable=False, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='You made appt at ')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='user1', max_length=200)),
                ('password', models.CharField(blank=True, default='password1', max_length=200)),
                ('has_appt', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='You made appt at ')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.clientlist')),
            ],
        ),
    ]
