# Generated by Django 4.1 on 2022-09-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perseverance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='defaults',
            field=models.IntegerField(default=-1000000000.0),
        ),
    ]
