# Generated by Django 4.1 on 2022-09-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perseverance', '0002_alter_balance_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='defaults',
            field=models.FloatField(default=-1000000000.0),
        ),
    ]
