# Generated by Django 4.1 on 2022-09-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perseverance', '0003_alter_balance_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='total_balance',
            field=models.FloatField(default=-1000000000.0),
        ),
    ]
