# Generated by Django 4.1 on 2022-09-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perseverance', '0004_balance_total_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='total_balance',
        ),
    ]
