# Generated by Django 4.1 on 2022-09-12 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perseverance', '0005_remove_balance_total_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='defaults',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_expense', models.CharField(max_length=200)),
                ('product', models.FloatField(default=-1000.0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perseverance.customer')),
            ],
            options={
                'verbose_name_plural': 'Income',
            },
        ),
    ]
